# modules/languages.py

WORLD_LANGUAGES = {
    "ka": "ქართული (Georgian)",
    "en": "ინგლისური (English)",
    "ru": "რუსული (Russian)",
    "de": "გერმანული (German)",
    "fr": "ფრანგული (French)",
    "es": "ესპანური (Spanish)",
    "it": "იტალიური (Italian)",
    "tr": "თურქული (Turkish)",
    "uk": "უკრაინული (Ukrainian)",
    "az": "აზერბაიჯანული (Azerbaijani)",
    "hy": "სომხური (Armenian)",
    "zh-CN": "ჩინური (Chinese Simplified)",
    "ja": "იაპონური (Japanese)",
    "ko": "კორეული (Korean)",
    "ar": "არაბული (Arabic)",
    "hi": "ჰინდი (Hindi)",
    "pt": "პორტუგალიური (Portuguese)",
    "nl": "ჰოლანდიური (Dutch)",
    "pl": "პოლონური (Polish)",
    "el": "ბერძნული (Greek)",
    "he": "ებრაული (Hebrew)",
    "sv": "შვედური (Swedish)",
    "no": "ნორვეგიული (Norwegian)",
    "fi": "ფინური (Finnish)",
    "da": "დანიური (Danish)",
    "cs": "ჩეხური (Czech)",
    "hu": "უნგრული (Hungarian)",
    "ro": "რუმინული (Romanian)",
    "bg": "ბულგარული (Bulgarian)",
    "sr": "სერბული (Serbian)",
    "hr": "ხორვატული (Croatian)",
    "sk": "სლოვაკური (Slovak)",
    "th": "ტაილანდური (Thai)",
    "vi": "ვიეტნამური (Vietnamese)",
    "id": "ინდონეზიური (Indonesian)",
    "ms": "მალაიზიური (Malay)",
    "fa": "პარსული (Persian)",
    "ur": "ურდუ (Urdu)",
    "kk": "ყაზახური (Kazakh)",
    "uz": "უზბეკური (Uzbek)"
}
