- name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgdbm-dev \
            libncurses5-dev \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libreadline-dev \
            tk-dev \
            gfortran \
            liblzma-dev \
            libjpeg-dev \
            ccache \
            zip \
            unzip \
            ninja-build \
            meson

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip setuptools wheel
          pip install "cython==0.29.33"
          pip install meson ninja
          pip install buildozer
